language: python
cache: pip
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - pip install -U pip wheel
  - pip install beautifulsoup4 flake8 lxml
  - ./setup.py test && flake8 .
